source "http://rubygems.org"
gem 'nokogiri'
gem 'ruby-bitly'
gem 'cinch'
gem 'time-lord'
gem 'weather-underground'
gem 'twitter'
gem 'rspec'
gem 'rspec-given'
gem 'file-tail'
gem 'tumblr-rb', '2.0.0'
gem 'crack', '0.1.7'
gem 'multi_json'
gem 'json', '1.7.7'
