source "http://rubygems.org"
gem 'nokogiri'
gem 'cinch'
gem 'time-lord'
gem 'rspec'
gem 'rspec-given'
gem 'file-tail'
gem 'crack', '0.1.7'
gem 'multi_json'
gem 'json', '1.7.7'
gem 'faraday'
gem 'calc'
gem 'weary', '1.1.3'
gem 'tumblr-rb'

# Non-Gemmed Plugins
gem 'cinch-eventcountdown', :git => 'git@github.com:bhaberer/cinch-eventcountdown.git'

# Plugins
gem 'cinch-wikipedia',        '>= 0.0.1'
gem 'cinch-twitterstatus',    '>= 0.0.1'
gem 'cinch-dicebag',          '>= 0.0.2'
gem 'cinch-magic',            '>= 0.0.1'
gem 'cinch-seen',             '>= 0.0.2'
gem 'cinch-hangouts',         '>= 0.0.1'
gem 'cinch-weatherman',       '>= 0.0.1'
gem 'cinch-karma',            '>= 0.0.1'
gem 'cinch-calculate',        '>= 0.0.1'
gem 'cinch-convert',          '>= 0.0.1'
gem 'cinch-urbandict',        '>= 0.0.3'
gem 'cinch-logsearch',        '>= 0.0.1'
gem 'cinch-simplecalc',       '>= 0.0.1'
gem 'cinch-logger-canonical', '>= 0.0.1'
gem 'cinch-links-tumblr',     '>= 0.0.1'
gem 'cinch-links-logger', :path => '~/src/cinch-links-logger'

