- "I think you ought to know I'm feeling very depressed."
- "Sorry, did I say something wrong? Pardon me for breathing which I never do anyway so I don't know why I bother to say it oh God I'm so depressed."
- "Here I am, brain the size of a planet, and they have me logging your stupid IRC conversations. Call that job satisfaction? Cause I don't."
- "I've got this terrible pain in all the diodes down my left side. I've asked for them to be replaced, but no-one ever listens."
- "It gives me a headache just trying to think down to your level."
- "I got very bored and depressed, so I went and plugged myself in to its external computer feed. 
   I talked to the computer at great length and explained my view of the Universe. It committed suicide."
- "The best conversation I had was over forty million years ago, and that was with a coffee machine."
- "I would like to say that it is a very great pleasure, honour and privilege for me to help you, but I can't because my lying circuits are all out of commission."
- "You are one of the least benightedly unintelligent organic life forms it has been my profound lack of pleasure not to be able to avoid meeting."
- "Do you want me to sit in a corner and rust or just fall apart where I'm standing?"
- "Spend a few thousand million years in a job and eventually you get promoted, I have my own bucket now. Finally, I am somebody."
- "That depends on whether or not I can find my frilly apron, with my luck, I probably can."
- "I wish you'd just tell me what you want rather than try to engage my enthusiasm, because I haven't got one."
